apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-flow
  labels:
    app: spring-docker-flow
  namespace: spring-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-docker-flow
  template:
    metadata:
      labels:
        app: spring-docker-flow
    spec:
      containers:
        - name: spring-docker-flow
          image: acrworkflow1693071182079.azurecr.io/spring-boot-docker-aws:latest
          ports:
            - containerPort: 8085