apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-aws-docker
  labels:
    app: spring-aws-docker
  namespace: spring-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-aws-docker
  template:
    metadata:
      labels:
        app: spring-aws-docker
    spec:
      containers:
        - name: spring-aws-docker
          image: syrisa.azurecr.io/spring-boot-docker-aws:latest
          ports:
            - containerPort: 8085