apiVersion: v1
kind: Service
metadata:
  name: spring-docker-flow
  namespace: namespace-workflow-1693071182079
spec:
  type: LoadBalancer
  selector:
    app: spring-docker-flow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080