apiVersion: v1
kind: Service
metadata:
  name: spring-docker-flow
  namespace: spring-docker
spec:
  type: LoadBalancer
  selector:
    app: spring-docker-flow
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
