apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdockeraws
  labels:
    team : springaws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recreate
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - name: springdockerawscon
        image: syr7s/spring-docker-aws:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
