apiVersion: apps/v1
kind: Deployment
metadata:
  name: springaws
  labels:
    team : springawsdevelopment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springaws
  template:
    metadata:
      labels:
        app: springaws
    spec:
      containers:
      - name: springdockerawscon
        image: syr7s/spring-docker-aws:v2
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "768m"
        ports:
        - containerPort: 8085
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 15
          periodSeconds: 20
        
          
