apiVersion: apps/v1
kind: Deployment
metadata:
  name: springaws
  labels:
    team : springawsdevelopment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springaws
  template:
    metadata:
      labels:
        app: springaws
    spec:
      containers:
      - name: springdockerawscon
        image: syr7s/spring-docker-aws:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
        
          
