apiVersion: v1
kind: Service
metadata:
  name: springaws
  labels:
    app: springaws
spec:
  type: NodePort
  ports:
    - port: 8085
      #protocol: TCP
      targetPort: 8085
      nodePort: 30500
  selector:
    app: springaws
